package com.iinfotechsystemsonline.app.utilities;

/**
 * Created by SOVAVY on 4/25/2017.
 */

public class Constants {


    public static final String EMPTY_STRING = "";
    public static final String VOLLEY_GET_TAG = "VOLLEY_GET_TAG";
    public static final String PREFS = "prefs";
    public static final String SELLLER_TYPE_LABEL = "Select Seller Type";
    public static final String SHOP_LABEL = "Shop";
    public static final String NAME_LABEL = "Enter name";
    public static final String SHOP_TYPE_LABEL = "Select Shop Type";
    public static final String HAWKER_TYPE_LABEL = "Select Hawker Type";
    public static final String HAWKER_LABEL = "Hawker";
    public static final String HAWKER_STATIONARY_LABEL = "Stationary";
    public static final String HAWKER_TRUCK_PUSHER_LABEL = "Mobile";
    public static final String SELLING_SPOT_LABEL = "Selling Spot";
    public static final String HAWKER_STATIONARY_FLOOR_LABEL = "Floor";
    public static final String HAWKER_STATIONARY_TABLE_LABEL = "Table";
    public static final String PICTURE_LABEL = "Take Picture";
    public static final String LOCATION_LABEL = "Get Location";
    public static final String PHONE_LABEL = "Enter Phone";
    public static final String SURNAME_LABEL = "Surname";
    public static final String FIRSTNAME_LABEL = "Firstname";
    public static final String SURNAME_DATA_KEY = "surname";
    public static final String FIRSTNAME_DATA_KEY = "firstname";
    public static final String SIMPLE_DATA_KEY = "_";
    public static final String PHONE_DATA_KEY = "phone";
    public static final String NETWORK_DATA_KEY = "network";
    public static final String COLON = ":";
    public static final String SHOP_LABEL_AND_SHOP_TYPE_LABEL = SHOP_LABEL + COLON + SHOP_TYPE_LABEL;
    public static final String HAWKER_LABEL_AND_HAWKER_TYPE_LABEL = HAWKER_LABEL
            + COLON + HAWKER_TYPE_LABEL;
    public static final String HAWKER_STATIONARY_LABEL_AND_SELLING_SPOT_LABEL = HAWKER_STATIONARY_LABEL
            + COLON
            + SELLING_SPOT_LABEL;
    public static final java.lang.String COMMA = ",";
    public static final String EMPTY = "";
    public static final String prefStringDefaultValue = "";
    public static final int prefIntDefualtValue = 0;
    public static final boolean prefBooleanDefault = false;
    public static final String STORE_URL = "";
    public static final String MOBILE_NETWORK_LABEL = "Mobile Network";
    public static final String WATER_INSTALLATION = "Water Installation";
    public static final String YES = "Yes";
    public static final String NO = "No";
    public static final String NUMBER_OF_UNIT_LABEL = "Number of Units within Building";
    public static final String ELECTRICITY_SOURCE_LABEL = "Electricity Source";
    public static final String PROPERTY_IDENTIFICATION_NUMBER_LABEL = "Property Indentification Number";
    public static final String INDENTURE_NUMBER_LABEL = "Indenture Number";
    public static final String RESIDENTIAL_CLASS_LABEL = "Residential Class";
    public static final String VEHICLE_PICTURE_LABEL = "Take License Plate Picture";
    public static final String DRIVER_LICENSE_NUMBER = "Enter Driver's License Number";
    public static final String VEHICLE_TYPE_LABEL = "Vehicle Type";
    public static final String CHOICE_LONG_BUSES_AND_TRUCKS = "Long buses and trucks";
    public static final String CHOICE_TRUCKS = "Trucks";
    public static final String CHOICE_SERVICE_CHARGE = "Service charge (table fee) per loading point";
    public static final String CHOICE_HOURLY = "Private vehicles - Hourly";
    public static final String CHOICE_DAILY = "Private vehicles - Daily";
    public static final String CHOICE_CARGO_TRUCK = "Cargo Truck";
    public static final String CHOICE_BUS = "Buses (44 Seater and above)";
    public static final String CHOICE_TROTRO = "Trotro (Mini Bus)";
    public static final String CHOICE_TAXI_CARAVAN = "Taxi/Caravan";
    public static final String UNION_AFFILIATION_LABEL = "Enter Union Affiliation";
    public static final String VEHICLE_MODEL_LABEL = "Enter Vehicle Model";
    public static final String VEHICLE_MAKE_LABEL = "Enter Vehicle Make";
    public static final String VEHICLE_YEAR_LABEL = "Enter Vehicle Year";
    public static final String VEHICLE_COLOR_LABEL = "Enter Vehicle Color";
    public static final String VEHICLE_TYPE_FREQUENCY_LABEL = "Vehicle Type And Frequency";
    public static final String MECHANIZED_LABEL = "Mechanized";
    public static final String CHOICE_BULLDOZER = "Bulldozer";
    public static final String CHOICE_TRUCK_CRANE = "Truck Crane";
    public static final String CHOICE_EXCAVATOR = "Excavator";
    public static final String CHOICE_FORKLIFT = "Forklift";
    public static final String CHOICE_GRADER = "Grader";
    public static final String CHOICE_WATER_TANKER = "Water Tanker";
    public static final String CHOICE_WATER_TANKERS = "Water Tankers";
    public static final String CHOICE_OTHER = "Other";
    public static final String CHOICE_OTHER_NAME = "Other Name";
    public static final String MECHANICAL_LABEL = "Mechanical";
    public static final String CHOICE_BICYCLE_PRIVATE = "Bicycle (Private)";
    public static final String CHOICE_BICYCLE_HIRE = "Bicycle (for Hire)";
    public static final String COMMERCIAL_DRIVERS_LICENSE_LABEL = "Commercial Driver's License";
    public static final String CHOICE_DRIVERS_LICENSE_APPLICATION_FORM = "Driver's License Application Form";
    public static final String CHOICE_REGISTRATION = "Registration";
    public static final String CHOICE_REPLACEMENT_OF_KMA_COMMERCIAL_DRIVERS_LINCENSE = "Replacement of K.M.A Commercial Driver's License";
    public static final String CHOICE_RENEWAL = "Renewal";
    public static final String COMMERCIAL_VEHICLE_EMBOSSMENT = "Commercial Vehicle Embossment";
    public static final String CONCRETE_MIXERS_VIBRATOR = "Concrete Mixers/Vibrator/Compressor etc.";
    public static final String CHOICE_CAT_A = "Category “A” (e.g. Two or More Machines)";
    public static final String CHOICE_CAT_B = "Category “B” (e.g. One Machine)";
    public static final String EARTH_ESCAVATION_LEVELING_PLANT_VEHICLES = "Earth Excavating/Leveling Plant/Vehicles";
    public static final String BITUMEN_DISTRIBUTOR = "Bitumen Distributer";
    public static final String BITUMEN_MIXER = "Bitumen Mixer";
    public static final String INTER_DISTRICT_BUSES_LONG_DISTANCE = "Inter - District Buses (Long Distance)";
    public static final String CHOICE_MINI_BUSES = "Mini Buses";
    public static final String CHOICE_UP_TO_33_SEATER_BUSES = "Up to 33-seater (Buses)";
    public static final String CHOICE_ABOVE_33_SEATER_BUSES = "Above 33-Seater (Buses)";
    public static final String INTER_CITY_TRANSPORT_SERVICES_AGENCIES = "Inter-City Transport Services Agencies";
    public static final String COMMERCIAL_LABEL = "Commercial or Not";
    public static final String CHOICE_NON_COMMERCIAL = "Non-commercial";
    public static final String CHOICE_COMMERCIAL = "Commercial";
    public static final String NON_COMMERCIAL_LABEL = "Non-Commercial Type";
    public static final String CHOICE_MINI_BUSES_PICKUPS_CROSS_COUNTRY = "Mini Buses/Pickups/Cross-Country Vehicles";
    public static final String CHOICE_MOTOR_CYCLES = "Motoer Cycles";
    public static final String CHOICE_SALOON = "Saloon Cars";
    public static final String CARGO_TRUCKS_LABEL = "CARGO TRUCKS";
    public static final String CHOICE_CARGO_CAT_A = "Category “A” (Above 5 Tonnes)";
    public static final String CHOICE_CARGO_CAT_B = "Category “B” (Up to 5-Tonnes e.g. Pick-Ups, Mini Buses)";
    public static final String CHOICE_CARGO_ARTICULATED = "Articulated Trucks";
    public static final String FUEL_TANKERS_LABEL = "Fuel Tankers";
    public static final String CHOICE_FUEL_TANKERS_CAT_A = "Category “A” (Articulated)";
    public static final String CHOICE_FUEL_TANKERS_CAT_B = "Category “B” (Non-Articulated)";
    public static final String CHOICE_CESSPIT_EMPTYING_VEHICLES = "Cesspit Emptying Vehicles";
    public static final String CHOICE_AMBULANCES_AND_HEARSE = "Ambulances/ Hearse";
    public static final String CHOICE_TOWING_CRANE = "Towing Vehicles/ Crane trucks";
    public static final String TRANSPORT_BUSINESS_LABEL = "Transport Business – Intercity";
    public static final String CHOICE_TRANSPORT_BUSINESS_CAT_A = "Category ‘A’ (e.g. V.I.P./ Coach Bus/ Luxury Bus)";
    public static final String CHOICE_TRANSPORT_BUSINESS_CAT_B = "Category ‘B’";
    public static final String STICKERS_LABEL = "Stickers";
    public static final String CHOICE_TAXI = "Taxi";
    public static final String CHOICE_TROTRO_UP_TO_17_SEATER = "Trotro up to 17 seater";
    public static final String CHOICE_TROTRO_18_AND_ABOVE = "Trotro 18 seater and above";
    public static final String CHOICE_TRICYCLE = "Tricycle (Aboboyaa)";
    public static final String CHOICE_TIPPER_TRUCKS = "Tipper Trucks";
    public static final String OWNER_PICTURE = "Take Owner Picture";
    public static final String OWNER_ID_PICTURE = "Take Picture of Government Issued License";
    public static final String OWNER_ID = "Enter ID Number";
    public static final String PET_PICTURE = "Take Pet Picture";
    public static final String PET_NAME_LABEL = "Enter Pet Name";
    public static final String PET_BREED_LABEL = "Select Breed of Pet";
    public static final String CHOICE_PET_EXOTIC = "Exotic Breed";
    public static final String CHOICE_PET_LOCAL_BREED = "Local Breed";
    public static final String PET_COLOR = "Enter pet color";
    public static final String PET_WEIGHT = "Enter pet weight";
    public static final String PET_SIZE = "Enter pet size";
    public static final String PET_HEIGHT = "Enter pet height";
    public static final String PET_AGE = "Enter pet age";
    public static final String VET_DOC_NAME = "Enter Veterinary Doctor's Name";
    public static final String VET_BUSINESS_REG_NUM = "Enter Veterinary Business Registration Number";
    public static final String VET_DOC_REG_NUM = "Enter Veterinary Doctor Registration Number";
    public static final String VET_DOC_PIN = "Enter Veterinary Doctor's Pin";
    public static final String VET_BUSINESS_ADDRESS = "Enter Veterinary Business Address";
    public static final String DATE_OF_VACCINATION = "Choose Date of Vaccination";
    public static final String TYPE_OF_VACCINATION = "Enter Type of Vaccination";
    public static final String VACCINATION_EXPIRY_DATE = "Choose Vaccination Expiry Date";
    public static final String PET_OWNER_NAME_LABEL = "Enter owner name";
    public static final String PET_OWNER_ADDRESS_LABEL = "Enter owner address";
    public static final String FUNERAL_UNDERTAKER_NAME_LABEL = "Enter Funeral Undertaker's Name";
    public static final String FUNERAL_UNDERTAKER_PERSONAL_ADDRESS_LABEL = "Funeral Undertaker's Personal Address";
    public static final String BUSINESS_REGISTRATION_NUMBER_LABEL = "Enter Business Registration Number";
    public static final String FUNERAL_UNDERTAKER_PHONE_NUMBER = "Enter Undertaker's Phone Numeber";
    public static final String FUNERAL_BUSINESS_REGISTRATION_LABEL = "Enter ";
    public static final String FUNERAL_REGISTERED_BUSINESS_NAME_LABEL = "Registered Business Number";
    public static final String FUNERAL_BUSINESS_ADDRESS_LABEL = "Enter Business Address";
    public static final String OWNER_PHOTO_LABEL = "Take the owner photo";
    public static final String GOVERNMENT_ISSUED_LICENSE = "Take Picture of Government Issued License";
    public static final String SERVICES_RENDER_LABEL = "Enter Service Rendered";
    public static final String BUSINESS_NAME_lABEL = "Business Name";
    public static final String DIRECTOR_NAME_LABEL = "Director Name";
    public static final String BUSINESS_REGISTRATION_NUMBER_lABEL = "Business Registration Number";
    public static final String ADDRESS_LABEL = "Enter Address";
    public static final String TYPE_OF_BUSINESS_LABEL = "Type of Business";
    public static final String TIN_NUMBER_LABEL = "Tin number";
    public static final String BUILDING_TYPE_LABEL = "Building Type";
    public static final String BUILDING_LEVEL_LABEL = "Building level";
    public static final String OWNERSHIP_STATUS_LABEL = "Ownership Status";
    public static final String REGISTRATION_STATUS_LABEL = "Registrations Status";
    public static final String prefsLogin = "prefslogin";
    public static final String prefsUsedBefore = "";
    public static final String GENDER_LABEL = "Gender";
    public static final String GENDER_MALE = "Male";
    public static final String GENDER_FEMALE = "Female";
    public static final String PAYMENT_TYPE = "Payment Type";
    public static final String DRIVER_LICENSE_PHOTO = "Take Driver's License Photo";
    public static final String PROPERTY_TYPE_LABEL = "Type of Property";
    public static final String PROPERTY_TYPE_COMMERCIAL_CHOICE = "Commercial";
    public static final String PROPERTY_TYPE_RESIDENTIAL_CHOICE = "Residential";
    public static final String PROPERTY_TYPE_INDUSTRIAL_CHOICE = "Industrial / Manufacturing";
    public static final String PROPERTY_TYPE_MIXED_USED_CHOICE = "Mixed Use";
    public static final String OWNER_NAME = "Owner name";
    public static final String OWNER_CONTACT = "Owner Contact";
    public static final String OCCUPANT_TYPE_LABEL = "Occupant Type";
    public static final String OCCUPANT_OWNER_TYPE_CHOICE = "Owner";
    public static final String OCCUPANT_RENTAL_TYPE_CHOICE = "Occupant";
    public static final String OCCUPANT_PICTURE_LABEL = "Occupant Picture";
    public static final String OCCUPANT_CONTACT_LABEL = "Occupant Contact";
    public static final String NUMBER_OF_OCCUPANTS_LABEL = "Number of People in the household over 18";
    public static final String OCCUPANT_ID = "ID picture of the occupant";
    public static final String ID_PICTURE_LABEL = "Take ID Picture";
    public static final String ID_TYPE_LABEL = "Select ID Type";
    public static final String VOTER_ID_CHOICE = "Voter ID";
    public static final String DRIVER_LICENCSE_CHOICE = "Driver License";
    public static final String SSNIT_NUMBER_CHOICE = "SSNIT No";
    public static final String STUDENT_ID_CHOICE = "Student ID";
    public static final String NHIS_CHOICE = "NHIS";
    public static final String NATIONAL_ID_CHOICE = "National ID";
    public static final String PASSPORT_CHOICE = "Passport";
    public static final String ID_NUMBER_LABEL = "Enter ID Number";
    public static final String PROPERTY_TYPE_OFFICE_CHOICE = "Office";
    public static final String STATE_OF_COMPLETION_LABEL = "State of Completion";
    public static final String AGE_OF_THE_PROPERTY = "Age of the Property";
    public static final String SUBMETRO_LABEL = "Submetro";
    public static final String PROPERTY_DESCRIPTION_LABEL = "Brief Description of the property";
    public static final String BUSINESS_DESCRIPTION_LABEL = "Brief Description of the business";
    public static final String PROPERTY_USE_LABEL = "Property Use";
    public static final String PROPERTY_LOCATION_LABEL = "Property Location";
    public static final String BUSINESS_LOCATION_LABEL = "Business Property Location";
    public static final String PROPERTY_ACTIVITY_LABEL = "Property Activity";
    public static final String PROPERTY_OBSERVATION_LABEL = "Observation";
    public static final String PROPERTY_PICTURE_LABEL = "Property Picture";

    public static final String PROPERTY_VALUE = "Valuation";
    public static final String AMOUNT_COLLECTED_LABEL = "Enter Amount Collected";
    public static final String RECEIPT_PICTURE_LABEL = "Take Receipt Picture";
    public static final String RECEIPT_NUMBER_LABEL = "Enter Receipt Number";
    public static final String AVAILABLE = "Is occupant available?";
    public static final String CHOICE_AVAILABLE = "available";
    public static final String CHOICE_NOT_AVAILABLE = "not available";
    public static final String VEHICLE_LICENSE_PLATE_LABEL = "Take a Picture of the Vehicle License Plate";
    public static final String VEHICLE_LICENCE_PLATE_NUMBER_LABEL = "Enter the Vehicle License Plate number";
    public static final String LOADING_BASE_LABEL = "Loading Base Location";
    public static final String FEES_LABEL = "Select Fees";
    public static final String CAR_PARKING_LABEL = "Car Parking";
    public static final String LORRY_PARK_USER_FEE_LABEL = "Lorry Park User Fees";
    public static final String UNAUTHORIZED_PARKING_LABEL = "Unauthorised parking and picking of passengers";
    public static final String VEHICLE_TOWING_AND_CLAMPING_LABEL = "Vehicle Towing and Clamping Fees";
    public static final String VEHICLE_SELECTION_LABEL = "Select Vehicle Type";
    public static final String SPOT_FINE_FOR_CARGO = "Spot fine for Cargo and Articulator trucks  within CBD after 9am";
    public static final String CAR_PARKING_CBD_LABEL = "Car Parking (CBD)";
    public static final String SELECT_CAR_PARKING = "Select Car Parking Type";
    public static final String PHONE_DATA_ONE_KEY = "phone1";
    public static final String PHONE_DATA_TWO_KEY = "phone2";
    public static final String PHONE_DATA_THREE_KEY = "phone3";
    public static final String RESPONDANT_NAME_LABEL = "Name of Respondent";
    public static final String OWNER_OR_NOT_OWNER_LABEL = "Is Respondent The Owner ?";
    public static final String CHOICE_UNDERVALUED = "Undervalued";
    public static final String CHOICE_OVERVALUED = "Overvalued";
    public static final String REMARKS_LABEL = "Remarks";
    public static final String SEARCH_KEY = "search_key";
    public static final String PHONE_ONE_LABEL = "Enter Phone Number";
    public static final String PHONE_TWO_LABEL = "Enter Another Optional Number";
    public static final String FIRE_RISK_CATEGORY_LABEL = "Select Risk category";
    public static final String FIRE_RISK_CATEGORY_HIGH_LABEL = "High risk";
    public static final String FIRE_RISK_CATEGORY_MEDIUM_LABEL = "Medium risk";
    public static final String FIRE_RISK_CATGORY_LOW_LABEL = "Low risk";
    public static final String FIRE_SERVICE_CERT_LABEL = "Fire service certificate";
    public static final String FIRE_EXTINGUISHER_LABEL = "Fire Extinguisher details";
    public static final String YES_LABEL = "Yes";
    public static final String NO_LABEL = "No";
    public static final String PIC_FIRE_CERT_LABEL = "Take Fire certificate picture";
    public static final String PIC_FIRE_EXTINGUISHER_LABEL = "Take Fire extinguisher label picture";
    public static final String INSURANCE_CERT_LABEL = "Do you have an Insurance Certificate";
    public static final String FIRE_CERT_NUMBER_LABEL = "Enter the fire certificate Number";
    public static final String PIC_INSURANCE_CERT_LABEL = "Take Insurance certificate picture";
    public static final String INSURANCE_ISSUE_DATE_LABEL = "Enter insurance issue date";
    public static final String FIRE_CERT_ISSUE_DATE_LABEL = "Enter fire certificate issue date";
    public static final String FIRE_EXTINGUISHER_ISSUE_DATE_LABEL = "Enter extinguisher issue date";
    public static final String FIRE_CERT_EXPIRY_DATE_LABEL = "Enter fire certificate expiry date";
    public static final String INSURANCE_EXPIRY_DATE_LABEL = "Enter insurance certificate expiry date";
    public static final String FIRE_EXTINGUISHER_EXPIRY_DATE_LABEL = "Enter fire extinguisher expiry date";
    public static final String FIRE_EXTINGUISHER_PROVIDER_LABEL = "Enter Provider name";
    public static final String INSURANCE_CERT_NUMBER_LABEL = "Enter insurance certificate Number";
    public static final String FIRE_EXTINGUISHER_EXPIRY_LABEL = "Do you have a fire extinguisher?";
    public static final String GHANA_POST_LABEL = "Enter GhanaPost Address";
    public static final String YES_LABEL_AND_FIRE_CERT_ISSUE_DATE_LABEL = YES_LABEL
            + COLON + FIRE_CERT_ISSUE_DATE_LABEL;
    public static final String YES_LABEL_AND_PIC_FIRE_CERT_LABEL = YES_LABEL
            + COLON + PIC_FIRE_CERT_LABEL;
    public static final String YES_LABEL_AND_FIRE_CERT_EXPIRY_DATE_LABEL = YES_LABEL
            + COLON + FIRE_CERT_EXPIRY_DATE_LABEL;
    public static final String YES_LABEL_AND_FIRE_RISK_CATEGORY_LABEL = YES_LABEL
            + COLON + FIRE_RISK_CATEGORY_LABEL;
    public static final String YES_LABEL_AND_FIRE_CERT_NUMBER_LABEL = YES_LABEL
            + COLON + FIRE_CERT_NUMBER_LABEL;
    public static final String YES_LABEL_AND_PIC_INSURANCE_CERT_LABEL = YES_LABEL
            + COLON + PIC_INSURANCE_CERT_LABEL;
    public static final String YES_LABEL_AND_INSURANCE_ISSUE_DATE_LABEL = YES_LABEL
            + COLON + INSURANCE_ISSUE_DATE_LABEL;
    public static final String YES_LABEL_AND_INSURANCE_EXPIRY_DATE_LABEL = YES_LABEL
            + COLON + INSURANCE_EXPIRY_DATE_LABEL;
    public static final String YES_LABEL_AND_INSURANCE_CERT_NUMBER_LABEL = YES_LABEL
            + COLON + INSURANCE_CERT_NUMBER_LABEL;
    public static final String YES_LABEL_AND_FIRE_EXTINGUISHER_PROVIDER_LABEL = YES_LABEL
            + COLON + FIRE_EXTINGUISHER_PROVIDER_LABEL;
    public static final String YES_LABEL_AND_FIRE_EXTINGUISHER_ISSUE_DATE_LABEL = YES_LABEL
            + COLON + FIRE_EXTINGUISHER_ISSUE_DATE_LABEL;
    public static final String YES_LABEL_AND_FIRE_EXTINGUISHER_EXPIRY_DATE_LABEL = YES_LABEL
            + COLON + FIRE_EXTINGUISHER_EXPIRY_DATE_LABEL;

    //      params.put("owner_type","");
//        params.put("name","");
//        params.put("geo_lng","");
//        params.put("geo_lat","");
//        params.put("accuracy","");
//        params.put("phone","");
//        params.put("nearest_landmark","");
//        params.put("description","");
//        params.put("ad_billboard_type_id","");
    public static final String SIGNAGE_OWNER_TYPE_LABEL = "Select the owner type";
    public static final String SIGNAGE_OWNER_NAME_LABEL = "Enter the owner name";
    public static final String SIGNAGE_GEOLOCATION_LABEL = "Get the location";
    public static final String SIGNAGE_OWNER_PHONE_LABEL = "Enter the owner phone";
    public static final String BUSINESS_OWNER_PHONE_LABEL = "Enter the owner phone";
    public static final String SIGNAGE_LANDMARK_LABEL = "Enter the nearest landmark";
    public static final String SIGNAGE_DESCRIPTION_LABEL = "Provide a description";
    public static final String SIGNAGE_NUM_FACES_LABEL = "Enter the number of faces";
    public static final String SIGNAGE_LAST_RENEWAL_DATE_LABEL = "Enter the last renewal date";
    public static final String SIGNAGE_CATEGORY_LABEL = "Select a category";
    public static final String SIGNAGE_OWNER_TYPE_INDIVIDUAL_CHOICE = "Individual";
    public static final String SIGNAGE_OWNER_TYPE_AGENCY_CHOICE= "Agency";
    public static final String SIGNAGE_IMAGE_LABEL = "Take a picture";
    public static final String PHYSICAL_ADDRESS_LABEL = "Enter Physical Address";
    public static final String POSTAL_ADDRESS_LABEL = "Enter Postal Address";
    public static final String NEAREST_LANDMARK_LABEL = "Nearest Landmark";
    public static final String OFFICIAL_PHONE_ONE_LABEL = "Enter Official Phone";
    public static final String DIRECTOR_PHONE_LABEL = "Enter Director's Phone (Optional)";
    public static final String OFFICIAL_PHONE_TWO_LABEL = "Enter Optional Phone";
    public static final String OWNER_PHONE_TWO_LABEL = "Enter Optional Owner Phone";
    public static final String PIC_CERTIFICATE_OF_COMMENCEMENT_LABEL = "Take certification of commencement picture";
    public static final String PIC_CERTIFICATE_OF_INCORPERATION_LABEL = "Take certification of incorperation picture";
    public static final String BUSINESS_TYPE_LABEL = "Select Business Type";


    public static String loadingDialogMsg;
    public static String serverAddress;
    public static int noNetworkMsg;


}